import React from "react";
import Head from 'next/head'

const Heads = () => {
	return (
		<>
			<Head>
				<title>Codewear</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='' />
			</Head>
		</>
	);
};

export default Heads;
